### ISSUE TITLE
Польза Builder'а для такого объекта

### ISSUE THREAD

**Issue by alexmikhalevich** [befozg/Pizzeria#4]
Для такого объекта нет смысла применять паттерн Builder. Говорил на позапрошлом и прошлом семинаре об этом.
https://github.com/Karen-1999/Pizzeria/blob/426eb7bdfde4bb2adadd0f4789cbe0f91f575a10/Product.h#L12

**Comment by alexmikhalevich** [comment]
Пицца как была мутабельной, так и осталась.

**Comment by befozg** [comment]
Сделал классы friend, setter-ы приватные, пицца immutable теперь
